"""Write ~/.config/hypr/desktopui-displays.conf so hyprctl reload reapplies desktopUI display layout."""

from __future__ import annotations

import os
from pathlib import Path


def desktopui_displays_conf_path() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "hypr" / "desktopui-displays.conf"


def ensure_desktopui_displays_conf_stub() -> None:
    """Create an empty-of-rules file so hyprland.conf source= never fails before first Apply."""
    path = desktopui_displays_conf_path()
    if path.is_file():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# desktopUI will add monitor= lines after Display Settings → Apply.\n"
        "# This file is sourced on hyprctl reload to keep outputs in sync.\n",
        encoding="utf-8",
    )


def write_desktopui_displays_conf(mode: str, single_output: str | None) -> None:
    """Emit monitor= lines matching desktopUI prefs (call after hyprctl apply or on the same tick)."""
    from services.displays_service import format_monitor_enable_spec, list_monitors_all

    all_mons = list_monitors_all()
    lines = [
        "# Generated by desktopUI — do not edit. Change layout in Display Settings.",
        "# Reloading Hyprland applies this file; it mirrors your last Apply.",
        "",
    ]
    mode = (mode or "").strip().lower()
    if not all_mons:
        lines.append("# (no outputs reported; open Display Settings when Hyprland is ready)")
        desktopui_displays_conf_path().parent.mkdir(parents=True, exist_ok=True)
        desktopui_displays_conf_path().write_text("\n".join(lines) + "\n", encoding="utf-8")
        return

    if mode == "single" and single_output and str(single_output).strip():
        one = str(single_output).strip()
        active_m = next(
            (m for m in all_mons if str(m.get("name", "")).strip() == one),
            None,
        )
        if active_m is not None:
            lines.append(f"monitor={format_monitor_enable_spec(active_m)}")
        for m in all_mons:
            n = str(m.get("name", "")).strip()
            if not n or n == one:
                continue
            lines.append(f"monitor={n},disable")
    elif mode == "all":
        for m in all_mons:
            n = str(m.get("name", "")).strip()
            if n:
                lines.append(f"monitor={format_monitor_enable_spec(m)}")
    else:
        lines.append(f"# Unknown mode {mode!r}; fix display_layout.json or re-apply in Display Settings.")

    path = desktopui_displays_conf_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
